# Generated by Django 2.0.5 on 2018-10-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ammount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_ID', models.IntegerField(unique=True)),
                ('Bank_Name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_ID', models.IntegerField(unique=True)),
                ('Cus_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='B_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='First_App.Bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='C_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='First_App.Customer'),
        ),
    ]
