# Generated by Django 2.0.5 on 2018-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Nick_name', models.CharField(max_length=255)),
                ('Bari', models.CharField(max_length=255)),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
